// Generated by: main
// TypeWriter: stringer
// Directive: +gen on astObjectFieldKind

package ast

import (
	"fmt"
)

const _astObjectFieldKind_name = "astObjectAssertastObjectFieldIDastObjectFieldExprastObjectFieldStrastObjectLocal"

var _astObjectFieldKind_index = [...]uint8{0, 15, 31, 49, 66, 80}

func (i ObjectFieldKind) String() string {
	if i < 0 || i+1 >= ObjectFieldKind(len(_astObjectFieldKind_index)) {
		return fmt.Sprintf("astObjectFieldKind(%d)", i)
	}
	return _astObjectFieldKind_name[_astObjectFieldKind_index[i]:_astObjectFieldKind_index[i+1]]
}
